### ISSUE TITLE
[tracking] support transfomer models

### ISSUE THREAD

**Issue by constroy** [InfiniTensor/InfiniTensor#112]
support transformer models, Bert, GPT-2, OPT and llama.

- [ ] `transepose`
- [ ] `sqrt` #109
- [ ] `gather` with index of int64 #94
- [ ] `where` #94 (operator only)
- [ ] `erf` #94 (operator only)

**Comment by constroy** [comment]
@PanZezhong1725  `transepose` can be ported from 34ed2987254ebb83ea0083f699f6564bc3876319
